/**
 * Unified HTML/CSS template for today.econ card news.
 * Single dark theme with news photo background, mascot, and casual editorial tone.
 * Optimized for Instagram 9:16 (1080x1920).
 */

/**
 * Dynamically highlights text wrapped in <hl> tags
 */
function highlightText(text, themeColor) {
  if (!text) return text;
  
  // Process explicit <hl> tags generated by the LLM
  let processed = text.replace(/<hl>(.*?)<\/hl>/gi, `<span style="color: ${themeColor}; font-weight: 900; border-bottom: 4px solid ${themeColor}60; padding-bottom: 2px;">$1</span>`);
  
  return processed;
}

/**
 * Renders the unified theme template
 */
function renderUnified(cardType, content, imageBase64, themeColor, newsDate = 'TODAY', mascotBase64 = '') {
  const mascotHtml = mascotBase64 
    ? `<img src="data:image/png;base64,${mascotBase64}" alt="오늘이" style="width: 120px; height: 120px; object-fit: contain; filter: drop-shadow(0 4px 12px rgba(0,0,0,0.5));" />`
    : '';

  let innerHtml = '';
  
  if (cardType === 'title') {
    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between py-16 px-16 select-none">
        <!-- Ambient Blur Background -->
        <div class="absolute inset-0 z-0 overflow-hidden">
          <img class="w-full h-full object-cover filter blur-[80px] opacity-35 scale-110" src="data:image/png;base64,${imageBase64}" alt="ambient" />
          <div class="absolute inset-0 bg-[#0f1724]/75"></div>
        </div>
        
        <!-- Top Header Area -->
        <header class="w-full max-w-[950px] mx-auto flex items-center justify-between z-20">
          <div class="flex items-center gap-4">
            <span class="inline-block px-5 py-2 rounded-full text-white/95 font-bold text-xl tracking-wider bg-white/10 border border-white/15 backdrop-blur-md">${newsDate}</span>
            <span class="text-white/40 font-black text-2xl tracking-wide">@today.econ</span>
          </div>
          <div class="w-20 h-20 flex items-center justify-center shrink-0">
            ${mascotHtml}
          </div>
        </header>

        <!-- Center Image Frame (Prevents Cropping) -->
        <div class="w-full max-w-[950px] mx-auto h-[620px] rounded-[32px] overflow-hidden border border-white/10 shadow-[0_25px_60px_rgba(0,0,0,0.6)] bg-black/35 flex items-center justify-center z-20 relative">
          <img class="w-full h-full object-contain" src="data:image/png;base64,${imageBase64}" alt="news image" />
        </div>

        <!-- Bottom Typography Area -->
        <main class="w-full max-w-[950px] mx-auto space-y-6 z-20 text-left">
          <div class="space-y-4">
            <h1 class="font-display text-[3.8rem] font-black text-white leading-[1.25] break-keep drop-shadow-[0_4px_15px_rgba(0,0,0,0.7)]">${highlightText(content.title.replace(/\\n/g, '<br/>'), themeColor)}</h1>
            <p class="font-body text-2.5xl text-white/70 break-keep leading-relaxed font-bold">${highlightText(content.subtitle, themeColor)}</p>
          </div>
          
          ${content.editors_insight ? `
            <div class="rounded-2xl p-6 flex items-center gap-6 backdrop-blur-2xl bg-white/[0.06] border border-white/10 shadow-[0_15px_35px_rgba(0,0,0,0.3)]">
              <p class="text-left text-white/90 leading-relaxed font-bold text-2xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
            </div>
          ` : ''}
        </main>
      </div>
    `;
  } else {
    const isFact = cardType === 'fact';
    const badgeText = isFact ? content.section_title || '무슨 일이야?' : content.section_title || '그래서 어떻게 돼?';
    const badgeBg = isFact ? `${themeColor}25` : '#10b98125';
    const badgeColor = isFact ? themeColor : '#34d399';
    const badgeBorder = isFact ? `${themeColor}50` : '#10b98150';

    const bulletsHtml = content.bullets
      .map((bullet, idx) => `
        <li class="flex items-start gap-5 py-3">
          <div class="w-10 h-10 rounded-full flex items-center justify-center shrink-0 mt-2" style="background: ${isFact ? themeColor + '20' : '#10b98120'}; border: 2px solid ${isFact ? themeColor + '40' : '#10b98140'};">
            ${isFact ? `
              <span class="w-3.5 h-3.5 rounded-full" style="background: ${themeColor};"></span>
            ` : `
              <svg class="w-5 h-5" style="color: ${badgeColor}" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3.5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
            `}
          </div>
          <p class="font-body text-[2rem] text-white/90 font-bold leading-relaxed break-keep bullet-text">${highlightText(bullet, themeColor)}</p>
        </li>
      `).join('<div class="w-full h-px bg-white/8 my-1"></div>');

    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between py-16 select-none">
        <!-- Ambient Blur Background for Inner Slides -->
        <div class="absolute inset-0 z-0 overflow-hidden">
          <img class="w-full h-full object-cover filter blur-[100px] opacity-20 scale-125" src="data:image/png;base64,${imageBase64}" alt="ambient" />
          <div class="absolute inset-0 bg-[#0f1724]/85"></div>
        </div>
        
        <main class="flex-1 flex flex-col z-20 justify-center px-16">
          <div class="w-full max-w-[950px] mx-auto rounded-[32px] p-11 space-y-7 bg-white/[0.06] backdrop-blur-xl border border-white/10 shadow-[0_30px_70px_rgba(0,0,0,0.5)]">
            <div class="mb-3">
              <span class="inline-block px-7 py-2.5 rounded-full font-bold text-[1.6rem] tracking-wider" style="background: ${badgeBg}; color: ${badgeColor}; border: 1px solid ${badgeBorder};">${badgeText}</span>
            </div>
            
            <ul class="space-y-3">
              ${bulletsHtml}
            </ul>

            ${content.hard_terms && content.hard_terms.length > 0 ? `
              <div class="mt-10 pt-7 border-t border-white/10">
                <div class="flex items-center gap-2 mb-4">
                  <span class="text-2xl" style="color: ${themeColor};">💡</span>
                  <span class="text-white/60 font-bold text-xl tracking-wider">쉽게 말하면?</span>
                </div>
                <div class="flex flex-wrap gap-3">
                  ${content.hard_terms.map(term => `
                    <div class="flex items-center gap-3 px-6 py-3 rounded-2xl bg-white/[0.06] border border-white/10">
                      <span style="color: ${themeColor};" class="font-black text-[1.4rem]">${term.term}</span>
                      <span class="text-white/20 text-xl">→</span>
                      <span class="text-white/70 font-bold text-[1.3rem]">${term.explanation}</span>
                    </div>
                  `).join('')}
                </div>
              </div>
            ` : ''}

            ${content.editors_insight ? `
              <div class="mt-8 pt-6 border-t border-white/10">
                <div class="flex items-start gap-4 rounded-2xl py-5 px-7 bg-white/[0.04] border-l-[5px]" style="border-left-color: ${themeColor};">
                  <p class="text-left text-white/80 leading-relaxed font-bold text-2xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
                </div>
              </div>
            ` : ''}
          </div>
          
          <div class="w-full max-w-[950px] mx-auto flex items-center justify-between mt-10 px-4">
            ${!isFact ? `
              <div class="text-center text-white/60 font-bold text-2xl py-3 px-8 rounded-full bg-white/[0.06] border border-white/10">
                오늘의 경제, 쉽고 빠르게 👉 <span style="color: ${themeColor};">[팔로우]</span>
              </div>
            ` : '<div></div>'}
            <div class="flex items-center gap-4">
              <span class="text-white/40 font-black text-2xl">@today.econ</span>
              <div class="w-16 h-16 flex items-center justify-center shrink-0">
                ${mascotHtml}
              </div>
            </div>
          </div>
        </main>
      </div>
    `;
  }


  return `
    <!DOCTYPE html>
    <html class="dark" lang="ko">
    <head>
      <meta charset="utf-8"/>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
      <title>today.econ Card</title>
      <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
      <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.css" />
      <script>
        tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                primary: "${themeColor}",
                background: "#0f1724"
              },
              fontSize: {
                '2.5xl': '1.75rem',
                '3.5xl': '2.1rem',
              },
              fontFamily: {
                sans: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                display: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                body: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"]
              }
            }
          }
        }
      </script>
      <style>
        body { background-color: #0f1724; overflow: hidden; margin: 0; padding: 0; }
        .slide-container { background-color: #0f1724; }
        .bullet-text { word-break: keep-all; }
        .insight-text { word-break: keep-all; }
      </style>
    </head>
    <body class="font-sans text-white antialiased flex items-center justify-center min-h-screen">
      ${innerHtml}
    </body>
    </html>
  `;
}

/**
 * Builds HTML code — now always uses the unified theme
 */
function buildThemeHtml(themeName, themeColor, cardType, content, imageBase64, newsDate, mascotBase64) {
  return renderUnified(cardType, content, imageBase64, themeColor, newsDate, mascotBase64);
}

module.exports = {
  buildThemeHtml,
};
