/**
 * Google Stitch designed HTML/CSS templates for today.econ card news.
 * Optimized for mobile (Instagram Reels / 9:16 Slides) with full-bleed visual layouts and premium typography.
 */

/**
 * Dynamically highlights text wrapped in <hl> tags and falls back to numbers/currencies
 */
function highlightText(text, themeColor) {
  if (!text) return text;
  
  // 1. First, keep the regex highlighting for numbers/currencies as a fallback
  const fallbackRegex = /(\b\d+(?:\.\d+)?(?:조|억|만)?(?:원|달러|%)?\b)/g;
  let processed = text.replace(fallbackRegex, `<span class="font-black" style="color: ${themeColor}">$1</span>`);
  
  // 2. Process explicit <hl> tags generated by the LLM (runs after so style attributes are not mutated)
  processed = processed.replace(/<hl>(.*?)<\/hl>/gi, `<span class="font-black" style="color: ${themeColor}; font-weight: 900; border-bottom: 4px solid ${themeColor}60; padding-bottom: 2px;">$1</span>`);
  
  return processed;
}

/**
 * Obsidian Theme (Dark Mode Premium Glassmorphism)
 */
function renderObsidian(cardType, content, imageBase64, themeColor, newsDate = 'TODAY') {
  let innerHtml = '';
  
  if (cardType === 'title') {
    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between p-16 select-none">
        <img class="absolute inset-0 w-full h-full object-cover z-0" src="data:image/png;base64,${imageBase64}" alt="illustration" />
        <div class="absolute inset-0 bg-gradient-to-b from-black/30 via-[#0A0E1A]/70 to-[#0A0E1A] z-10"></div>
        <div class="ambient-glow glow-primary w-[700px] h-[700px] bottom-[-200px] right-[-200px] z-10"></div>
        
        <!-- Header removed for cleaner UI -->

        <main class="flex-1 flex flex-col z-20 justify-end pb-24 mt-24 space-y-10">
          <!-- Full bleed typography, no modal container -->
          <div class="w-full max-w-[950px] mx-auto space-y-6 text-left px-4">
            <div>
              <span class="inline-block px-8 py-2.5 rounded-full bg-primary/20 border border-primary/40 text-primary font-label-caps text-2xl tracking-widest backdrop-blur-md">${newsDate}</span>
            </div>
            <h1 class="font-display text-7xl font-black text-white leading-tight break-keep drop-shadow-[0_4px_16px_rgba(0,0,0,0.9)]">${highlightText(content.title.replace(/\n/g, '<br/>'), themeColor)}</h1>
            <p class="font-body text-4xl text-slate-200 break-keep leading-relaxed font-black drop-shadow-[0_4px_10px_rgba(0,0,0,0.8)]">${highlightText(content.subtitle, themeColor)}</p>
          </div>
          
          ${content.editors_insight ? `
            <div class="w-full max-w-[950px] mx-auto rounded-[28px] p-8 flex items-center gap-6 backdrop-blur-2xl bg-[#0A0E1A]/85 border border-white/10 shadow-[0_20px_50px_rgba(0,0,0,0.6)]">
              <div class="w-1.5 h-16 bg-primary rounded-full shadow-[0_0_10px_rgba(0,210,255,0.6)] shrink-0"></div>
              <p class="text-left text-slate-100 leading-normal font-extrabold text-2.5xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
            </div>
          ` : ''}
          
          <div class="footer-area text-slate-400 font-black text-center text-2.5xl drop-shadow-[0_4px_6px_rgba(0,0,0,0.9)]">@today.econ</div>
        </main>
      </div>
    `;
  } else {
    const isFact = cardType === 'fact';
    const badgeText = isFact ? content.section_title || '무슨 일이야?' : content.section_title || '그래서 어떻게 돼?';
    const badgeBg = isFact ? `${themeColor}20` : '#10b98120';
    const badgeColor = isFact ? themeColor : '#10b981';
    const badgeBorder = isFact ? `${themeColor}40` : '#10b98140';

    const bulletsHtml = content.bullets
      .map(bullet => `
        <li class="flex items-start gap-6 py-4">
          <div class="w-12 h-12 rounded-full bg-slate-900/80 flex items-center justify-center border ${isFact ? 'border-primary/40' : 'border-primary/20'} shrink-0 mt-1.5 shadow-[0_0_15px_${isFact ? themeColor : themeColor}40]">
            ${isFact ? `
              <span class="w-4 h-4 rounded-full bg-primary"></span>
            ` : `
              <svg class="w-6 h-6 text-primary/80" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
            `}
          </div>
          <p class="font-body text-3.5xl text-slate-100 font-extrabold leading-normal break-keep bullet-text">${highlightText(bullet, themeColor)}</p>
        </li>
      `).join('<div class="w-full h-px bg-white/5 my-1"></div>');

    // Layout Variation: Fact is centered wide card, Action is bottom drawer anchored
    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between p-16 select-none">
        <img class="absolute inset-0 w-full h-full object-cover z-0" src="data:image/png;base64,${imageBase64}" alt="illustration" />
        <div class="absolute inset-0 bg-gradient-to-b from-black/40 via-[#0A0E1A]/80 to-[#0A0E1A] z-10"></div>
        <div class="ambient-glow glow-primary w-[700px] h-[700px] bottom-[-200px] right-[-200px] z-10"></div>
        
        <!-- Header removed for cleaner UI -->

        <main class="flex-1 flex flex-col z-20 ${isFact ? 'justify-center mt-16' : 'justify-end pb-16'}">
          <div class="glass-card w-full max-w-[950px] mx-auto rounded-[36px] p-12 space-y-8 shadow-[0_30px_70px_rgba(0,0,0,0.7)] border border-white/10 ${!isFact ? 'mb-8' : ''}">
            <div class="mb-4">
              <span class="inline-block px-8 py-2.5 rounded-full font-label-caps text-2xl tracking-wider" style="background: ${badgeBg}; color: ${badgeColor}; border: 1px solid ${badgeBorder};">${badgeText}</span>
            </div>
            
            <ul class="space-y-4">
              ${bulletsHtml}
            </ul>

            ${content.hard_terms && content.hard_terms.length > 0 ? `
              <div class="mt-6 flex flex-wrap gap-3">
                ${content.hard_terms.map(term => `
                  <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-800/80 border border-white/5 shadow-inner">
                    <span class="text-primary font-bold text-xl">${term.term}</span>
                    <span class="text-slate-500 text-xl">|</span>
                    <span class="text-slate-300 text-xl">${term.explanation}</span>
                  </div>
                `).join('')}
              </div>
            ` : ''}

            ${content.editors_insight ? `
              <div class="mt-8 pt-8 border-t border-white/10 flex items-start gap-4 text-primary bg-primary/5 rounded-2xl py-5 px-6">
                <div class="w-1 h-12 bg-primary rounded-full shrink-0"></div>
                <p class="text-left text-slate-200 leading-normal font-extrabold text-2.5xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
              </div>
            ` : ''}
          </div>
          
          <div class="w-full flex flex-col items-center space-y-6">
            ${!isFact ? `
              <div class="cta-banner w-full text-center text-slate-200 font-bold text-2.5xl py-4 px-8 rounded-full backdrop-blur-2xl bg-black/60 border border-white/10 shadow-[0_15px_35px_rgba(0,0,0,0.5)] max-w-[950px] mx-auto">
                오늘의 경제, 내일도 쉽고 빠르게 👉 <span style="color: ${themeColor}; text-shadow: 0 0 8px ${themeColor}80;">[팔로우]</span>
              </div>
            ` : ''}
            <div class="footer-area text-slate-400 font-black text-center text-2.5xl drop-shadow-[0_4px_6px_rgba(0,0,0,0.9)]">@today.econ</div>
          </div>
        </main>
      </div>
    `;
  }

  return `
    <!DOCTYPE html>
    <html class="dark" lang="ko">
    <head>
      <meta charset="utf-8"/>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
      <title>today.econ Obsidian Card</title>
      <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
      <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>
      <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.css" />
      <script>
        tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                primary: "${themeColor}",
                "primary-container": "${themeColor}",
                background: "#0A0E1A"
              },
              fontSize: {
                '2.5xl': '1.75rem',
                '3.5xl': '2.1rem',
              },
              fontFamily: {
                sans: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                display: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                body: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"]
              }
            }
          }
        }
      </script>
      <style>
        body { background-color: #0A0E1A; overflow: hidden; }
        .glass-card {
          background-color: rgba(10, 14, 26, 0.85);
          backdrop-filter: blur(40px);
          -webkit-backdrop-filter: blur(40px);
          border: 1px solid rgba(255, 255, 255, 0.08);
        }
        .ambient-glow {
          position: absolute;
          border-radius: 50%;
          filter: blur(120px);
          z-index: 5;
          pointer-events: none;
        }
        .glow-primary {
          background: radial-gradient(circle, ${themeColor}15 0%, transparent 70%);
        }
        .slide-container {
          background-color: #0A0E1A;
        }
        .bullet-text {
          word-break: keep-all;
        }
        .insight-text {
          word-break: keep-all;
        }
      </style>
    </head>
    <body class="font-sans text-white antialiased flex items-center justify-center min-h-screen">
      ${innerHtml}
    </body>
    </html>
  `;
}

/**
 * Ivory Theme (Light Mode Premium Editorial)
 */
function renderIvory(cardType, content, imageBase64, themeColor, newsDate = 'TODAY') {
  let innerHtml = '';
  
  if (cardType === 'title') {
    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between p-16 select-none">
        <img class="absolute inset-0 w-full h-full object-cover z-0" src="data:image/png;base64,${imageBase64}" alt="illustration" />
        <div class="absolute inset-0 bg-gradient-to-b from-[#FDFBF7]/20 via-[#FDFBF7]/70 to-[#FDFBF7] z-10"></div>
        
        <!-- Header removed for cleaner UI -->

        <main class="flex-1 flex flex-col z-20 justify-end pb-24 mt-24 space-y-10">
          <!-- Full bleed typography, no modal container -->
          <div class="w-full max-w-[950px] mx-auto space-y-6 text-left px-4">
            <div>
              <span class="inline-block px-8 py-2.5 rounded bg-slate-800 text-white font-label-caps text-2xl tracking-widest">${newsDate}</span>
            </div>
            <h1 class="font-display text-7xl font-black text-slate-800 leading-tight break-keep drop-shadow-[0_2px_8px_rgba(255,255,255,0.8)]">${highlightText(content.title.replace(/\n/g, '<br/>'), themeColor)}</h1>
            <p class="font-body text-4xl text-slate-700 break-keep leading-relaxed font-black drop-shadow-[0_2px_6px_rgba(255,255,255,0.8)]">${highlightText(content.subtitle, themeColor)}</p>
          </div>
          
          ${content.editors_insight ? `
            <div class="w-full max-w-[950px] mx-auto rounded-[28px] p-8 flex items-center gap-6 backdrop-blur-2xl bg-[#FDFBF7]/90 border border-slate-200/80 shadow-[0_15px_40px_rgba(0,0,0,0.06)]">
              <div class="w-1.5 h-16 bg-slate-800 rounded-full shrink-0"></div>
              <p class="text-left text-slate-800 leading-normal font-extrabold text-2.5xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
            </div>
          ` : ''}
          
          <div class="footer-area text-slate-500 font-black text-center text-2.5xl drop-shadow-[0_4px_6px_rgba(255,255,255,0.8)]">@today.econ</div>
        </main>
      </div>
    `;
  } else {
    const isFact = cardType === 'fact';
    const badgeText = isFact ? content.section_title || '무슨 일이야?' : content.section_title || '그래서 어떻게 돼?';
    
    // Ivory Theme palette (Fact: deep gold, Action: warm terracotta/orange)
    const badgeColor = isFact ? '#705d00' : '#c2410c';
    const badgeBg = isFact ? 'rgba(112, 93, 0, 0.08)' : 'rgba(194, 65, 12, 0.08)';
    const badgeBorder = isFact ? 'rgba(112, 93, 0, 0.2)' : 'rgba(194, 65, 12, 0.2)';

    const bulletsHtml = content.bullets
      .map(bullet => `
        <li class="flex items-start gap-6 py-4">
          <div class="w-12 h-12 rounded-full bg-white/90 flex items-center justify-center border ${isFact ? 'border-[#705d00]/30' : 'border-[#c2410c]/30'} shrink-0 mt-1.5 shadow-[0_0_15px_${isFact ? 'rgba(112,93,0,0.15)' : 'rgba(194,65,12,0.15)'}]">
            ${isFact ? `
              <span class="w-4 h-4 rounded-full" style="background-color: ${badgeColor}"></span>
            ` : `
              <svg class="w-6 h-6" style="color: ${badgeColor}" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
            `}
          </div>
          <p class="font-body text-3.5xl text-slate-800 font-extrabold leading-normal break-keep bullet-text">${highlightText(bullet, themeColor)}</p>
        </li>
      `).join('<div class="w-full h-px bg-slate-200/60 my-1"></div>');

    // Layout Variation: Fact is centered wide card, Action is bottom drawer anchored
    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between p-16 select-none">
        <img class="absolute inset-0 w-full h-full object-cover z-0" src="data:image/png;base64,${imageBase64}" alt="illustration" />
        <div class="absolute inset-0 bg-gradient-to-b from-[#FDFBF7]/40 via-[#FDFBF7]/80 to-[#FDFBF7] z-10"></div>
        
        <!-- Header removed for cleaner UI -->

        <main class="flex-1 flex flex-col z-20 ${isFact ? 'justify-center mt-16' : 'justify-end pb-16'}">
          <div class="glass-card w-full max-w-[950px] mx-auto rounded-[36px] p-12 space-y-8 shadow-[0_20px_45px_rgba(0,0,0,0.06)] ${!isFact ? 'mb-8' : ''}">
            <div class="mb-4">
              <span class="inline-block px-8 py-2.5 rounded font-label-caps text-2xl tracking-wider" style="background: ${badgeBg}; color: ${badgeColor}; border: 1px solid ${badgeBorder};">${badgeText}</span>
            </div>
            
            <ul class="space-y-4">
              ${bulletsHtml}
            </ul>

            ${content.hard_terms && content.hard_terms.length > 0 ? `
              <div class="mt-6 flex flex-wrap gap-3">
                ${content.hard_terms.map(term => `
                  <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/60 border border-slate-200/50 shadow-sm">
                    <span class="text-secondary font-bold text-xl">${term.term}</span>
                    <span class="text-slate-300 text-xl">|</span>
                    <span class="text-slate-600 text-xl">${term.explanation}</span>
                  </div>
                `).join('')}
              </div>
            ` : ''}

            ${content.editors_insight ? `
              <div class="mt-8 pt-8 border-t border-slate-200/80 flex items-start gap-4 text-secondary bg-secondary/5 rounded-2xl py-5 px-6">
                <div class="w-1 h-12 bg-secondary rounded-full shrink-0"></div>
                <p class="text-left text-slate-700 leading-normal font-extrabold text-2.5xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
              </div>
            ` : ''}
          </div>
          
          <div class="w-full flex flex-col items-center space-y-6 ${isFact ? 'mt-12' : ''}">
            ${!isFact ? `
              <div class="cta-banner w-full text-center text-slate-800 font-bold text-2.5xl py-4 px-8 rounded-full backdrop-blur-2xl bg-white/70 border border-slate-200 shadow-[0_10px_25px_rgba(0,0,0,0.05)] max-w-[950px] mx-auto">
                오늘의 경제, 내일도 쉽고 빠르게 👉 <span style="color: ${themeColor}; text-shadow: 0 0 4px ${themeColor}40;">[팔로우]</span>
              </div>
            ` : ''}
            <div class="footer-area text-slate-500 font-black text-center text-2.5xl">@today.econ</div>
          </div>
        </main>
      </div>
    `;
  }

  return `
    <!DOCTYPE html>
    <html lang="ko">
    <head>
      <meta charset="utf-8"/>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
      <title>today.econ Ivory Card</title>
      <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
      <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>
      <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.css" />
      <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                primary: "#121212",
                secondary: "#705d00"
              },
              fontSize: {
                '2.5xl': '1.75rem',
                '3.5xl': '2.1rem',
              },
              fontFamily: {
                sans: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                display: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                body: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"]
              }
            }
          }
        }
      </script>
      <style>
        body {
          background-color: #FDFBF7;
          overflow: hidden;
        }
        .glass-card {
          background: rgba(253, 251, 247, 0.9);
          backdrop-filter: blur(30px);
          border: 1px solid rgba(255, 255, 255, 0.95);
        }
        .bullet-text {
          word-break: keep-all;
        }
        .insight-text {
          word-break: keep-all;
        }
      </style>
    </head>
    <body class="font-sans text-slate-800 antialiased flex items-center justify-center min-h-screen">
      ${innerHtml}
    </body>
    </html>
  `;
}

/**
 * Cyber Theme (Neon Purple/Pink Futuristic Cyberpunk)
 */
function renderCyber(cardType, content, imageBase64, themeColor, newsDate = 'TODAY') {
  let innerHtml = '';
  
  if (cardType === 'title') {
    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between p-16 select-none">
        <img class="absolute inset-0 w-full h-full object-cover z-0" src="data:image/png;base64,${imageBase64}" alt="illustration" />
        <div class="absolute inset-0 bg-gradient-to-b from-[#140727]/30 via-[#140727]/70 to-[#140727] z-10"></div>
        
        <!-- Header removed for cleaner UI -->

        <main class="flex-1 flex flex-col z-20 justify-end pb-24 mt-24 space-y-10">
          <!-- Full bleed typography, no modal container -->
          <div class="w-full max-w-[950px] mx-auto space-y-6 text-left px-4">
            <div>
              <span class="inline-block px-8 py-2.5 rounded border border-secondary text-secondary font-label-caps text-2xl tracking-widest shadow-[0_0_12px_rgba(255,75,137,0.5)]">${newsDate}</span>
            </div>
            <h1 class="font-display text-7xl font-black text-white leading-tight break-keep drop-shadow-[0_4px_16px_rgba(0,0,0,0.9)]">${highlightText(content.title.replace(/\n/g, '<br/>'), themeColor)}</h1>
            <div class="w-32 h-1.5 bg-primary shadow-[0_0_15px_rgba(235,178,255,0.9)] mt-2"></div>
            <p class="font-body text-4xl text-slate-200 break-keep leading-relaxed font-black drop-shadow-[0_4px_10px_rgba(0,0,0,0.8)]">${highlightText(content.subtitle, themeColor)}</p>
          </div>
          
          ${content.editors_insight ? `
            <div class="w-full max-w-[950px] mx-auto rounded-[28px] p-8 flex items-center gap-6 backdrop-blur-2xl bg-[#140727]/85 border border-[#ebb2ff]/20 shadow-[0_20px_50px_rgba(0,0,0,0.6)]">
              <div class="w-1.5 h-16 bg-primary rounded-full shadow-[0_0_15px_rgba(235,178,255,0.8)] shrink-0"></div>
              <p class="text-left text-slate-200 leading-normal font-extrabold text-2.5xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
            </div>
          ` : ''}
          
          <div class="footer-area text-slate-400 font-black text-center text-2.5xl drop-shadow-[0_4px_6px_rgba(0,0,0,0.9)]">@today.econ</div>
        </main>
      </div>
    `;
  } else {
    const isFact = cardType === 'fact';
    const badgeText = isFact ? content.section_title || '무슨 일이야?' : content.section_title || '그래서 어떻게 돼?';
    const badgeBorderColor = isFact ? '#ebb2ff' : '#ffb1c3';
    const badgeGlowColor = isFact ? 'rgba(235,178,255,0.4)' : 'rgba(255,177,195,0.4)';
    const dotBorder = isFact ? 'border-primary/50' : 'border-secondary/50';
    const dotPulseColor = isFact ? 'bg-primary' : 'bg-secondary';
    const bulletGlow = isFact ? 'rgba(235,178,255,0.4)' : 'rgba(255,177,195,0.4)';

    const bulletsHtml = content.bullets
      .map(bullet => `
        <li class="flex items-start gap-6 py-4">
          <div class="w-12 h-12 rounded-full bg-slate-900/60 flex items-center justify-center border ${dotBorder} shrink-0 mt-1.5 shadow-[0_0_15px_${bulletGlow}]">
            <span class="w-4 h-4 rounded-full ${dotPulseColor} animate-pulse"></span>
          </div>
          <p class="font-body text-3.5xl text-slate-100 font-extrabold leading-normal break-keep bullet-text">${highlightText(bullet, themeColor)}</p>
        </li>
      `).join('<div class="w-full h-px bg-white/10 my-2"></div>');

    // Layout Variation: Fact is centered wide card, Action is bottom drawer anchored
    innerHtml = `
      <div class="slide-container relative w-[1080px] h-[1920px] overflow-hidden flex flex-col justify-between p-16 select-none">
        <img class="absolute inset-0 w-full h-full object-cover z-0" src="data:image/png;base64,${imageBase64}" alt="illustration" />
        <div class="absolute inset-0 bg-gradient-to-b from-[#140727]/40 via-[#140727]/80 to-[#140727] z-10"></div>
        
        <!-- Header removed for cleaner UI -->

        <main class="flex-1 flex flex-col z-20 ${isFact ? 'justify-center mt-16' : 'justify-end pb-16'}">
          <div class="glass-card w-full max-w-[950px] mx-auto rounded-[36px] p-12 space-y-8 shadow-[0_20px_50px_rgba(0,0,0,0.4)] border border-[#ebb2ff]/20 ${!isFact ? 'mb-8' : ''}">
            <div class="mb-4">
              <span class="inline-block px-8 py-2.5 rounded border text-slate-200 font-label-caps text-2xl tracking-widest uppercase" style="border-color: ${badgeBorderColor}; background: ${badgeBorderColor}15; box-shadow: 0 0 10px ${badgeGlowColor};">${badgeText}</span>
            </div>
            
            <ul class="space-y-4">
              ${bulletsHtml}
            </ul>

            ${content.hard_terms && content.hard_terms.length > 0 ? `
              <div class="mt-6 flex flex-wrap gap-3">
                ${content.hard_terms.map(term => `
                  <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-black/40 border border-primary/30 shadow-[0_0_10px_rgba(235,178,255,0.1)]">
                    <span class="text-primary font-bold text-xl">${term.term}</span>
                    <span class="text-slate-600 text-xl">|</span>
                    <span class="text-slate-300 text-xl">${term.explanation}</span>
                  </div>
                `).join('')}
              </div>
            ` : ''}

            ${content.editors_insight ? `
              <div class="mt-8 pt-8 border-t border-white/10 flex items-start gap-4 text-primary bg-primary/5 rounded-2xl py-5 px-6">
                <div class="w-1 h-12 bg-primary rounded-full shadow-[0_0_10px_rgba(235,178,255,0.6)] shrink-0"></div>
                <p class="text-left text-slate-200 leading-normal font-extrabold text-2.5xl insight-text">${highlightText(content.editors_insight, themeColor)}</p>
              </div>
            ` : ''}
          </div>
          
          <div class="w-full flex flex-col items-center space-y-6 ${isFact ? 'mt-12' : ''}">
            ${!isFact ? `
              <div class="cta-banner w-full text-center text-slate-200 font-bold text-2.5xl py-4 px-8 rounded-full backdrop-blur-2xl bg-black/60 border border-white/10 shadow-[0_15px_35px_rgba(0,0,0,0.5)] max-w-[950px] mx-auto">
                오늘의 경제, 내일도 쉽고 빠르게 👉 <span style="color: ${themeColor}; text-shadow: 0 0 8px ${themeColor}80;">[팔로우]</span>
              </div>
            ` : ''}
            <div class="footer-area text-slate-500 font-black text-center text-2.5xl">@today.econ</div>
          </div>
        </main>
      </div>
    `;
  }

  return `
    <!DOCTYPE html>
    <html class="dark" lang="ko">
    <head>
      <meta charset="utf-8"/>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
      <title>today.econ Cyber Card</title>
      <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
      <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>
      <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.css" />
      <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                primary: "#ebb2ff",
                secondary: "#ffb1c3",
                tertiary: "#2ae500",
                background: "#190c2c"
              },
              fontSize: {
                '2.5xl': '1.75rem',
                '3.5xl': '2.1rem',
              },
              fontFamily: {
                sans: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                display: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
                body: ["Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"]
              }
            }
          }
        }
      </script>
      <style>
        body { background-color: #140727; overflow: hidden; }
        .glass-card {
          background: rgba(20, 7, 39, 0.85);
          backdrop-filter: blur(25px);
          -webkit-backdrop-filter: blur(25px);
          border: 1px solid rgba(235, 178, 255, 0.2);
        }
        .text-neon-green {
          color: #39FF14;
          text-shadow: 0 0 10px rgba(57, 255, 20, 0.5);
        }
        .bg-radial-glow {
          background: radial-gradient(circle at 50% 0%, rgba(188, 19, 254, 0.3) 0%, rgba(24, 11, 43, 0) 60%),
                      radial-gradient(circle at 100% 100%, rgba(255, 75, 137, 0.2) 0%, rgba(24, 11, 43, 0) 50%);
        }
        .slide-container {
          background-color: #140727;
        }
        .bullet-text {
          word-break: keep-all;
        }
        .insight-text {
          word-break: keep-all;
        }
      </style>
    </head>
    <body class="bg-radial-glow font-sans text-on-background font-body-md antialiased flex items-center justify-center min-h-screen">
      ${innerHtml}
    </body>
    </html>
  `;
}

/**
 * Builds HTML code dynamically based on selected theme
 */
function buildThemeHtml(themeName, themeColor, cardType, content, imageBase64, newsDate) {
  const normalized = (themeName || 'obsidian').toLowerCase();
  
  if (normalized === 'ivory') {
    return renderIvory(cardType, content, imageBase64, themeColor, newsDate);
  } else if (normalized === 'cyber') {
    return renderCyber(cardType, content, imageBase64, themeColor, newsDate);
  } else {
    return renderObsidian(cardType, content, imageBase64, themeColor, newsDate);
  }
}

module.exports = {
  buildThemeHtml,
};
